yamlversion: 2
updates:
    - package-ecosystem: "composer"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "monday"
      open-pull-requests-limit: 10
      versioning-strategy: increase-if-necessary
      labels:
          - "dependencies"
      ignore:
          # Ignorer les mises à jour majeures
          - dependency-name: "*"
            update-types: ["version-update:semver-major"]